import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@0;1&family=Roboto:wght@400;500&display=swap" rel="stylesheet" />
        <title>Roleta</title>
        <link rel="shortcut icon" href="https://sempresupra.com.br/wp-content/uploads/2020/03/sempre-supra-fav-new.png" type="image/png" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}